### ISSUE TITLE
Make http_pins.py Python3 friendly

### ISSUE THREAD

**Issue by dmak** [StalkR/misc#7]
Would be nice if you could port `crypto/http_pins.py` to Python3. Unfortunately I don't have an experience to fix non-trivial issues:
```
# python3 http_pins.py server.pem
server.pem:
Traceback (most recent call last):
  File "http_pins.py", line 97, in <module>
    main(sys.argv)
  File "http_pins.py", line 85, in main
    spki = extract_spki(cert)
  File "http_pins.py", line 30, in extract_spki
    out = proc.communicate()[0].strip().split('\n')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by StalkR** [comment]
sure no problem

**Comment by dmak** [comment]
Thanks, fantastic!
